export const mockData = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/fUkjt1C7V5RAKnkpLaiZy3hJ7xh.jpg',
      genre_ids: [27, 28],
      id: 36647,
      original_language: 'en',
      original_title: 'Blade',
      overview:
        'The Daywalker known as "Blade" - a half-vampire, half-mortal man - becomes the protector of humanity against an underground army of vampires.',
      popularity: 52.102,
      poster_path: '/hx0sdduAsr4rq03RZKZzglR25z7.jpg',
      release_date: '1998-08-21',
      title: 'Blade',
      video: false,
      vote_average: 6.768,
      vote_count: 5584,
    },
    {
      adult: false,
      backdrop_path: '/hFtJz4TvoiJJcw2ZOMdhK22aU9P.jpg',
      genre_ids: [14],
      id: 617127,
      original_language: 'en',
      original_title: 'Blade',
      overview:
        'A film set in the Marvel Cinematic Universe (MCU) based on the Marvel Comics character of the same name.',
      popularity: 14.616,
      poster_path: '/fKqA4rgVJwrM7Gb3tQ9TGHnu8Tr.jpg',
      release_date: '2025-11-05',
      title: 'Blade',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/jXFuYhZlJb55nwZa3fcGXPVTWGD.jpg',
      genre_ids: [53, 9648],
      id: 107331,
      original_language: 'en',
      original_title: 'Blade',
      overview:
        'A homicide detective goes after a woman-hating serial killer, who uses knives to murder his victims.',
      popularity: 2.629,
      poster_path: '/odycG85vK9CMU77eDxMkzxPyEYn.jpg',
      release_date: '1973-12-01',
      title: 'Blade',
      video: false,
      vote_average: 5.357,
      vote_count: 7,
    },
    {
      adult: false,
      backdrop_path: '/8JKc1ZJTMcSprhYtUD2IegsX77L.jpg',
      genre_ids: [28, 14, 16],
      id: 46304,
      original_language: 'ja',
      original_title: 'Fate/stay night UNLIMITED BLADE WORKS',
      overview:
        "Shirou Emiya finds himself an unwilling participant in a deadly competition where seven Mages summon heroic spirits as servants to duel each other to the death. They compete for the chance to make a wish from the Holy Grail, which has the power to grant any wish. Shirou is unskilled as a mage and knows nothing of the Holy Grail War, but he and his servant, Saber, enter into a temporary partnership with another Mage, Rin Tohsaka. However, problems arise between Shirou and Rin's servant, Archer, who seems to seriously despise him.",
      popularity: 12.848,
      poster_path: '/oElUusJLyLnbgIwHDZsSu1aJ9Ik.jpg',
      release_date: '2010-12-17',
      title: 'Fate/stay night: Unlimited Blade Works',
      video: false,
      vote_average: 7.036,
      vote_count: 69,
    },
    {
      adult: false,
      backdrop_path: '/ilRyazdMJwN05exqhwK4tMKBYZs.jpg',
      genre_ids: [878, 18],
      id: 335984,
      original_language: 'en',
      original_title: 'Blade Runner 2049',
      overview:
        "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos. K's discovery leads him on a quest to find Rick Deckard, a former LAPD blade runner who has been missing for 30 years.",
      popularity: 116.793,
      poster_path: '/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
      release_date: '2017-10-04',
      title: 'Blade Runner 2049',
      video: false,
      vote_average: 7.551,
      vote_count: 12703,
    },
    {
      adult: false,
      backdrop_path: '/wtzJihFG4aBTat6QG9BoOWud7rG.jpg',
      genre_ids: [28, 14, 12],
      id: 426284,
      original_language: 'ja',
      original_title: '無限の住人',
      overview:
        'Manji, a highly skilled samurai, becomes cursed with immortality after a legendary battle. Haunted by the brutal murder of his sister, Manji knows that only fighting evil will regain his soul. He promises to help a young girl named Rin avenge her parents, who were killed by a group of master swordsmen led by ruthless warrior Anotsu. The mission will change Manji in ways he could never imagine.',
      popularity: 16.026,
      poster_path: '/bFaxg006Dt6J1k7qa7a5YuqbAhe.jpg',
      release_date: '2017-04-29',
      title: 'Blade of the Immortal',
      video: false,
      vote_average: 6.6,
      vote_count: 492,
    },
    {
      adult: false,
      backdrop_path: '/3C05fY5KvxfmPLp1exBSX8c0Q0K.jpg',
      genre_ids: [28, 16, 878],
      id: 475946,
      original_language: 'en',
      original_title: 'ブレードランナー ブラックアウト 2022',
      overview:
        'This animated short revolves around the events causing an electrical systems failure on the west coast of the US. According to Blade Runner 2049’s official timeline, this failure leads to cities shutting down, financial and trade markets being thrown into chaos, and food supplies dwindling. There’s no proof as to what caused the blackouts, but Replicants — the bio-engineered robots featured in the original Blade Runner, are blamed.',
      popularity: 17.514,
      poster_path: '/zzRjnUOVXyjp2WudgT7KxJLYh9D.jpg',
      release_date: '2017-09-26',
      title: 'Blade Runner: Black Out 2022',
      video: false,
      vote_average: 7.2,
      vote_count: 359,
    },
    {
      adult: false,
      backdrop_path: '/rnNkUJlo03a8D0utxiOrADstaMT.jpg',
      genre_ids: [12, 36, 28, 14],
      id: 300168,
      original_language: 'zh',
      original_title: '天將雄師',
      overview:
        'Huo An, the commander of the Protection Squad of the Western Regions, was framed by evil forces and becomes enslaved. On the other hand, a Roman general escapes to China after rescuing the Prince. The heroic duo meet in the Western Desert and a thrilling story unfolds.',
      popularity: 17.207,
      poster_path: '/suTAWYLIHAnkH2V4nC8t3AG7HjR.jpg',
      release_date: '2015-02-19',
      title: 'Dragon Blade',
      video: false,
      vote_average: 6.35,
      vote_count: 528,
    },
    {
      adult: false,
      backdrop_path: '/mXEKGETmIJ9jkVoA8FuEb17uFb9.jpg',
      genre_ids: [28, 80, 27],
      id: 45233,
      original_language: 'en',
      original_title: 'I violenti',
      overview:
        'Emanuelle, a reporter, comes just a little too close to exposing a corrupt official, and is sent to prison on trumped-up charges. In the prison, the inmates are constantly humiliated and tortured by the prison staff.',
      popularity: 26.394,
      poster_path: '/ivEWHvm5EiF4eb2l0ieZdz4DRkq.jpg',
      release_date: '1983-05-06',
      title: 'Blade Violent',
      video: false,
      vote_average: 4.3,
      vote_count: 52,
    },
    {
      adult: false,
      backdrop_path: '/eIi3klFf7mp3oL5EEF4mLIDs26r.jpg',
      genre_ids: [878, 18, 53],
      id: 78,
      original_language: 'en',
      original_title: 'Blade Runner',
      overview:
        'In the smog-choked dystopian Los Angeles of 2019, blade runner Rick Deckard is called out of retirement to terminate a quartet of replicants who have escaped to Earth seeking their creator for a way to extend their short life spans.',
      popularity: 68.093,
      poster_path: '/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg',
      release_date: '1982-06-25',
      title: 'Blade Runner',
      video: false,
      vote_average: 7.9,
      vote_count: 13065,
    },
    {
      adult: false,
      backdrop_path: '/g8cjJHZFeZQ5GRbFiDp5jXgfOZW.jpg',
      genre_ids: [14, 27, 28, 53],
      id: 36586,
      original_language: 'en',
      original_title: 'Blade II',
      overview:
        'A rare mutation has occurred within the vampire community - The Reaper. A vampire so consumed with an insatiable bloodlust that they prey on vampires as well as humans, transforming victims who are unlucky enough to survive into Reapers themselves. Blade is asked by the Vampire Nation for his help in preventing a nightmare plague that would wipe out both humans and vampires.',
      popularity: 49.727,
      poster_path: '/wAn6VYamKbnOtfyTZ6arVtkMzDv.jpg',
      release_date: '2002-03-22',
      title: 'Blade II',
      video: false,
      vote_average: 6.525,
      vote_count: 4429,
    },
    {
      adult: false,
      backdrop_path: '/3DKq152scTsUv0ygEh6vSXbrNX.jpg',
      genre_ids: [10749, 28, 18, 36],
      id: 457837,
      original_language: 'zh',
      original_title: '绣春刀II：修罗战场',
      overview:
        'An imperial guard searches for the truth behind a conspiracy that framed him and his partners. The proof of his innocence lies with a wanted woman named Bei Zhai... but will she reveal what she knows? In this intense prequel to BROTHERHOOD OF BLADES, the only thing he can truly trust is his sword.',
      popularity: 15.108,
      poster_path: '/bQ2fdFCcmCSDuI62JU9pVNTN7c4.jpg',
      release_date: '2017-06-18',
      title: 'Brotherhood of Blades II: The Infernal Battlefield',
      video: false,
      vote_average: 6.8,
      vote_count: 83,
    },
    {
      adult: false,
      backdrop_path: '/dAO1VXJ1FkTCElVsnSWUicbWFKT.jpg',
      genre_ids: [18, 28, 53],
      id: 34179,
      original_language: 'zh',
      original_title: '錦衣衛',
      overview:
        'Commander Qinglong is the loyal leader of the assassin group that serves the emperor. But when his allies plan a rebellion against the ruler, he finds himself in danger.',
      popularity: 21.532,
      poster_path: '/y1VWOEN0UXFiSgCNvWO3lQuzLx.jpg',
      release_date: '2010-02-04',
      title: '14 Blades',
      video: false,
      vote_average: 6.32,
      vote_count: 181,
    },
    {
      adult: false,
      backdrop_path: '/dlnngBRu37QSZrpCligR89NADAL.jpg',
      genre_ids: [28, 18],
      id: 67097,
      original_language: 'zh',
      original_title: '一刀傾城',
      overview:
        'Wang Wu, A kung-fu expert, is depressed about the dismal state of the political affairs of China. But, when he meets another famous kung-fu master, they together decide to bring about a revolution.',
      popularity: 8.516,
      poster_path: '/g5A67fliLJPX61J50LRY3SJvdBI.jpg',
      release_date: '1993-07-15',
      title: 'Blade of Fury',
      video: false,
      vote_average: 7.1,
      vote_count: 16,
    },
    {
      adult: false,
      backdrop_path: '/55885wQeb8XISRccwnfVJ7DDJFM.jpg',
      genre_ids: [28, 27, 14],
      id: 36648,
      original_language: 'en',
      original_title: 'Blade: Trinity',
      overview:
        'For years, Blade has fought against the vampires in the cover of the night. But now, after falling into the crosshairs of the FBI, he is forced out into the daylight, where he is driven to join forces with a clan of human vampire hunters he never knew existed—The Nightstalkers. Together with Abigail and Hannibal, two deftly trained Nightstalkers, Blade follows a trail of blood to the ancient creature that is also hunting him—the original vampire, Dracula.',
      popularity: 31.014,
      poster_path: '/rodqqX8NLe3cdcgBMc4CFTPidTy.jpg',
      release_date: '2004-12-08',
      title: 'Blade: Trinity',
      video: false,
      vote_average: 5.853,
      vote_count: 3640,
    },
    {
      adult: false,
      backdrop_path: '/txhPl1nfQSFeQOya9gxP7hBsbBD.jpg',
      genre_ids: [99, 36, 10770],
      id: 833898,
      original_language: 'de',
      original_title: 'Das Phänomen Blade Runner',
      overview:
        "Ridley Scott's cult film Blade Runner, based on a novel by Philip K. Dick and released in 1982, is one of the most influential science fiction films ever made. Its depiction of Los Angeles in the year 2019 is oppressively prophetic: climate catastrophe, increasing public surveillance, powerful monopolistic corporations, highly evolved artificial intelligence; a fantastic vision of the future world that has become a frightening reality.",
      popularity: 7.337,
      poster_path: '/2ANJtUxqBlCLpV8CXv3BPLo0FV5.jpg',
      release_date: '2021-05-27',
      title: 'The Blade Runner Phenomenon',
      video: false,
      vote_average: 6.786,
      vote_count: 7,
    },
    {
      adult: false,
      backdrop_path: '/2CWJTgfU8SGRZ25hn8L6iujATvk.jpg',
      genre_ids: [14],
      id: 732459,
      original_language: 'en',
      original_title: 'Blade of the 47 Ronin',
      overview:
        'In this sequel to "47 Ronin," a new class of warriors emerges among the Samurai clans to keep a sought-after sword from falling into the wrong hands.',
      popularity: 28.882,
      poster_path: '/kjFDIlUCJkcpFxYKtE6OsGcAfQQ.jpg',
      release_date: '2022-10-25',
      title: 'Blade of the 47 Ronin',
      video: false,
      vote_average: 6.575,
      vote_count: 187,
    },
    {
      adult: false,
      backdrop_path: '/13AW2aCagb14IL2QPUptcNe1I9e.jpg',
      genre_ids: [36, 18, 28, 10752],
      id: 62977,
      original_language: 'zh',
      original_title: '关云长',
      overview:
        "During the warring period of the three kingdoms, ancient China is in turmoil. To unify the country, general Cao Cao, the real power behind the Emperor, enlists the aid of the greatest warrior in the land, Guan Yu. However, Guan Yu is a loyal friend of Cao Cao's enemy Liu Bei so to persuade the peerless warrior to fight, Cao Cao takes his beloved Qi Lan hostage. After leading Cao Cao's forces to victory Guan Yu sets out with Qi Lan to rejoin Liu Bei. Now Cao Cao has deemed him too great a threat to live, and on the journey he must face all the forces at the Emperor's command sent to destroy him.",
      popularity: 9.744,
      poster_path: '/rBYeOpWSMzw18DKR3sCkyKdChxa.jpg',
      release_date: '2011-04-28',
      title: 'The Lost Bladesman',
      video: false,
      vote_average: 6.333,
      vote_count: 99,
    },
    {
      adult: false,
      backdrop_path: '/4G8p4OZrWMs27xDLVMuFadEdM7X.jpg',
      genre_ids: [10749, 28, 18],
      id: 291692,
      original_language: 'zh',
      original_title: '绣春刀',
      overview:
        'In the late Ming Dynasty, three sworn brothers who serve as the imperial secret police are dispatched to hunt down Wei Zhongxian, a eunuch politician who had been forced to resign from his influential post and exiled from Beijing. The brothers return successfully from their quest, only to find that their task was but the beginning of a strange conspiracy.',
      popularity: 13.715,
      poster_path: '/d2mXV6VXqpxxv5Zet9xc2rKVpJz.jpg',
      release_date: '2014-08-07',
      title: 'Brotherhood of Blades',
      video: false,
      vote_average: 6.6,
      vote_count: 140,
    },
    {
      adult: false,
      backdrop_path: '/92HhhtM2yT0ffV1kAkVDv16an9b.jpg',
      genre_ids: [18, 28],
      id: 42845,
      original_language: 'cn',
      original_title: '刀',
      overview:
        'A young man adopted by a renowned swordsmith, discovers that his real father was killed by a powerful bandit called Lung. Leaving to seek revenge, he runs foul of a group of vicious desert scum, losing his right arm in the process. After being nursed back to health, he eventually learns to compensate for his loss and returns to confront the man who murdered his father.',
      popularity: 11.81,
      poster_path: '/jLH5MxiYXtGiS96rl13Rz8TIPaG.jpg',
      release_date: '1995-12-21',
      title: 'The Blade',
      video: false,
      vote_average: 7.1,
      vote_count: 95,
    },
  ],
  total_pages: 13,
  total_results: 257,
}
